# Generated by Django 3.0.6 on 2021-11-05 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.BigIntegerField(verbose_name='budget')),
                ('genres', models.CharField(max_length=2000, verbose_name='genres')),
                ('homepage', models.CharField(max_length=2000, verbose_name='homepage')),
                ('keywords', models.CharField(max_length=2000, verbose_name='keywords')),
                ('original_language', models.CharField(max_length=2000, verbose_name='original_language')),
                ('original_title', models.CharField(max_length=2000, verbose_name='original_title')),
                ('overview', models.CharField(max_length=2000, verbose_name='overview')),
                ('popularity', models.FloatField(verbose_name='popularity')),
                ('release_date', models.CharField(max_length=2000, verbose_name='release_date')),
                ('tagline', models.CharField(max_length=2000, verbose_name='tagline')),
                ('title', models.CharField(max_length=2000, verbose_name='title')),
                ('vote_average', models.IntegerField(verbose_name='vote_average')),
                ('cast', models.CharField(max_length=2000, verbose_name='cast')),
                ('director', models.CharField(max_length=2000, verbose_name='director')),
            ],
        ),
        migrations.AddField(
            model_name='mylist',
            name='movies',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recommend.Movies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myrating',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommend.Movies'),
            preserve_default=False,
        ),
    ]
