# Generated by Django 3.0.6 on 2021-12-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_moviess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Moviess'),
        ),
        migrations.AlterField(
            model_name='myrating',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Moviess'),
        ),
    ]
