# Generated by Django 3.0.6 on 2021-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20211210_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviesss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='title')),
                ('genres', models.CharField(max_length=2000, verbose_name='genres')),
                ('keywords', models.CharField(max_length=2000, verbose_name='keywords')),
                ('cast', models.CharField(max_length=2000, verbose_name='cast')),
                ('director', models.CharField(max_length=2000, verbose_name='director')),
                ('images', models.CharField(max_length=2000, verbose_name='images')),
            ],
        ),
    ]
